### PR TITLE
[WIP] Feature/13/homescreenwidget v2

### PR DESCRIPTION
**Pull request by newhinton**
see #15

### CODE REVIEW

**Comment by newhinton** [comment]
Currently this does not support Lists stored on the internal storage

**Comment by newhinton** [comment]
Todo:

- [ ] Configurationscreen Overhaul
- [ ] List reordering
- [ ] List switching

**Comment by lolo-io** [comment]
Just tested it, works as expected so far :) Thanks !
I just fixed List reordering. Can you allow me to push on your PR ?
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by lolo-io** [comment]
Or if you prefer I can do a PR on your fork. Which do you prefer ?

**Comment by newhinton** [comment]
@lolo-io you should already be able to make edits to this branch, as per link you posted maintainers should be able to make edits

**Comment by lolo-io** [comment]
Yes my bad the rejected push was due to a bad github config on my side.
I've pushed list reordering on your pr branch. I use the same code that is used to reorder lists when an item is checked/unchecked within the app.
I have refactored it as a fiunction of ListItem.

**Pull request closed without merging**
