### PR TITLE
Show undo dialog when deleting and store deleted items

### PR DESCRIPTION
**Pull request by newhinton**
This does not discard deleted items anymore. When you delete an item, it gets stored in a deletedItems list with a timestamp when it was deleted. Currently there will be a snackbar at the bottom of the screen that allows to undo a deletetion. In the future, we could implement a way to permanently delete entries or bring back entries that were deleted a long time ago.

### CODE REVIEW

**Comment by newhinton** [comment]
I do not reorder the list. Is there a sorting function for that?

**Comment by newhinton** [comment]
Todo:

- [ ] Fix Snackbar-Typo
- [ ] List reordering

**Optional:**

Todo:

- [ ] Build UI to show all deleted entries

**Comment by newhinton** [comment]
closes #16

**Comment by newhinton** [comment]
Generally, you are right, "deleted" is redundant in the current state. However, my line of thought was that we use this to store the timestamp when it was deleted. Maybe that is unnessessary, idk. Generally my "long term goal" is to write a nextcloud-app which can display onelist-lists, and that could make use of the advanced features that keeping the deleted items. 
Also, as a benefit, no listitems are really lost, even if someone would miss his chance to undo a delete. 

Therefore, i would like to keep the deleted entrylist with the timestamps, however, i could compromise on the deleted timestamp. I mean, if you really dont want that, ill only keep the undo-action, but i'd really like to see the other stuff :D 

Also, we could wait with a merge until i have something to present on the nextcloud side of things if you want

**Comment by lolo-io** [comment]
I like the idea, but i'd like to keep the code free of "unnecesary at the moment" code as long as the nexcloud side is not ready. This is for cleaner code and easier maintainance purposes.
But i'll be glad to implement it  when needed. 
I'm ok to keep the "undo" part, without the deleted attribute in the list nor in the items, for now.

**Pull request closed without merging**
