### PR TITLE
Storage fix and other features

### LINKED ISSUE #10: [Feature] Optional reordering when done
Hi, first of all thanks a lot for your app and releasing it as Open Source, never found an app like this one which fit my needs

The only issue I have with it is that it reorders a todo element when I validate it as done

This feature is interesting for reusable lists (like a weekly todo list that I want to keep in a specific order)

It could be an option when creating the todo list, but it would impact the file save, as the sharing

### LINKED ISSUE #26: Default storage folder is ignored
I want to set the "Default storage folder" to "/storage/emulated/0" because then I can access the file(s) for making a backup of it.

But the app ignores this and stores the settings and my lists always here:
/data/data/com.lolo.io.onelist/shared_prefs/MainActivity.xml

### LINKED ISSUE #27: Please let the order of the list-items as they are
When clicking on a list-item to mark it as done I would prefer the following behavior:
The item ist moved down into the "done" area, but in the same position as it was before clicking.

When cliking again on it, it should appear in the same position as in the beginning.

Reason:
When making a shopping list for a specific shop, I often buy the same things (e.g. bread, etc.).
Therefore the list is ordered in the same order as they are appearing when I walk through the shop.
In the current situation I have to re-order the list every time before I go shopping.

If this is not possible, the list-items could be just left in its place and just marked as "done".
Making this configurable is probably preferable.

### LINKED ISSUE #32: Let user decide if items are added to top or bottom of list
Wow, this is a pretty decent app! Very compatible with my workflow and looking great!

There's just one thing I notice in a lot of list apps that I can't wrap my head around: why are new items added to the _top_ of the list instead of the bottom? When you guys write a list on a piece of paper or in a text editor do you write from bottom to top?! I'm seriously curious, I guess this is one of those cases where there's two kinds of people...

Anyhow, I would welcome a setting to add new items to the bottom of the list instead of top. Also, if I can easily change this in the source code I'd be glad to build my own customized version of the app. I guess the relevant function is addItem() in OneListFragment.kt? Does this line mean it's added to the top of the list? (Is the 0 the position in the list or something else?)

	selectedList.items.add(0, item)

If anyone can tell me how to change it to insert new items at the bottom of the list I'll be happy to hear it!

### LINKED ISSUE #38: Export/Import lists
Hi, I cannot import lists that I exported before (as a .txt). 
Can you please tell me how to properly do it?
Other than that the app is the best todo app.
Thank you!

### LINKED ISSUE #41: Error while getting your list from content
using Google version on Android 10

i started getting this error every time i start the app after i 
changed the "Default storage folder"  over to my sd card.

Error while getting your list from content: 
 //com.android.externalstorage.documents/tree/primary%3A1list/document/primary%3A1list%2F<listname-longnumericvalue>.1list
Displaying cached one instead.

i get this for each list i have everytime i access the app.

using a file manager i see a folder with  files under it
on the SD card, one for each list.   the timestamp on the
files seems to imply they are being updated.

### PR DESCRIPTION
**Pull request by lrq3000**
This PR is based on the `develop` branch and it implements the following changes:

* restore support for an external folder using scoped storage permissions via [SimpleStorage](https://github.com/anggrayudi) library. Note that due to how permissions now work, the filetype defines the file extension, so that all files now are `.1list.json` instead of `.1list` as before (EDIT: in fact it's possible to force a custom file extension by not specifying a `mimeType` in `makeFile()` in `PersistenceHelper.kt`, but then it may be risky in the future, maybe Android may confuse this with a `MediaStore` file and restrict permission if it is unsure it's a `DocumentFile`, so I would rather keep `.1list.json` just to be sure, and also 3rd-party reading apps can more easily open these files). Big thanks to @anggrayudi for his help with making this possible despite Google's insanity! (See issues [here](https://github.com/anggrayudi/SimpleStorage/issues/110) and [here](https://github.com/anggrayudi/SimpleStorage/issues/111)). Fixes #41, fixes #26 and fixes #38.
* a Share All Lists button as a quick workaround to export a backup of all lists easily.
* option for Share and Share All export in Markdown or plain text.
* option to add new tasks at the list's end instead of top. Fixes #32.
* option to NOT move done tasks. Fixes #10 and fixes #27.
* option when editing a task to move it to another list. A typical use case is to move urgent tasks to an "URGENT" list, and when done or not urgent anymore, it can be moved back to its original list such as "Errands" or "Work". Given how the app's main utility revolves around multitasking and navigating quickly around multiple lists, I feel this feature is totally in the app's ethos.

For those who are impatient, a debug APK is available here: https://github.com/lrq3000/OneList/releases/tag/storage-fix-and-more-features-bugfix5

Important note: this PR increases the minimum API from 16 to 19 to support the minimum libraries required for SimpleStorage to work, so by merging this we drop support for Android versions older than 19 (KITKAT). 

@lolo-io This PR is fully functional, and if you don't like the additional features, you can just cherry-pick whichever commits you want, I rebased to separate them cleanly.

However there are a few minor things that could be improved:
* [x] Currently, the Share and Share All functions are represented by 2 different buttons. They could be merged into one, with a dialog being created to allow user to select between "Share this list" or "Share all lists".
* [x] In the Preferences, I added an option "storage_force" which, when clicked, copies all lists into the new default path. I implemented this to ease the transition of current users, so they can easily copy all their lists to the new storage. Although this option is not destructive, it would be better if it asked the user to confirm before being applied, to avoid misclicks. 
* [x] bug: can move new tasks to the very bottom of the list, then trying to move it will make the app crash. New tasks with option "Add to the bottom" should be created at the bottom but before done tasks!
* [x] bug: when force storage update, path of lists are not updated on UI in EditListDialog until app is closed and reopened
* [x] bug: force storage update not working when selecting App private storage, should just delete list.path
* [ ] portugues translations are missing for my additions, so it's in english until someone translate in this language. But the French translation is done. (won't do, I cannot translate in portuguese unfortunately, help is welcome!)

~As you can see, these are very minor issues, it's just that I am not experienced enough with making dialogs. We only need very simple dialogs to make these two options perfectly fine. This can be done at a later point in time.~ This is now done.

Also note that I left `Log.d` calls on purpose, as they are anyway muted and skipped in the compiled app, but are very helpful if we ever need to debug storage issues again (especially if users need to debug! You can ask for a dump and it will tell you right away where there is an issue and if permissions were correctly granted).

### CODE REVIEW

**Comment by lrq3000** [comment]
@lolo-io did you have time to have a look? Please let me know if you need me to change something :-)

**Comment by lrq3000** [comment]
Also I've been using the devug apk for a week now on a daily basis, everything seems to work very fine!

**Comment by lrq3000** [comment]
@lolo-io just to let you know that I did a last pass of polishing on thes PR to clean up all remaining issues such as implementing confirmation dialogs and some edge case errors, except portuguese translation, so this PR can be merged without additional work.

**Comment by lrq3000** [comment]
Four months later I am still using this build in production, combined with SyncThing to make a backup to a computer, and it works flawlessly. It is very stable, it can be merged whenever you want @lolo-io .

**Comment by lolo-io** [comment]
Hi @lrq3000. A am back on this project after a long time of absence.
I have been working lately on a new way of handling stored lists on the device.
The way it was done initially was experimental and I didn't like that much the fact that each lists could be saved in its own folder. That made storage management very painful to maintain/manage/predict. The majority of people will assign only y one of their folders to 1List, so I headed up this way. 
Now you can just chose if your lists (all lists) will be backed up in the one folder you chose. This is done from the settings and not the list options.

I also wasn't happy with the codebase, so I refactored all of it to make it more aligned with nowadays coding standards. There is still work to do on that side but I'm on it. The consequence is that all previous PRs are totally out of date now.

I want to thank you for your PR even if I didn't merge it. It was very useful, I looked into it during my refacto. I used SimpleStorage as you advised me. 
The reasons I didn't merge it was 1- I needed to make sure no user would loose their lists while updating to the new version, 2- I still wasn't satisfied about this storage feature, so I already wanted to rethink it to make it more user friendly, and 3- Th PR was very big, with a lot of different stuff to review/test, or even to chose to implement or not. Making cherry-picks on other's PR's isn't an enjoyable task 😅, so I ended up postponing it forever.

Anyway, thanks for the support. Sorry for having been away so long, 
I will close this PR because now it is totally desychronized from master.

**Comment by lrq3000** [comment]
No problem, thank you @lolo-io for your huge work refactoring your great app and I'm glad if my code could help at least with some parts of the implemeetation, SimpleStorage is an awesome library that makes our lives easier as Android devs 😄

**Pull request closed without merging**
